config/routes.rb
Rails.application.routes.draw do


  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  resources :events do 
  		resources :attendees , :controller => :event_attendees

  		collection do
  			get :latest
  			post :bulk_update
  		end

  		member do 
  			get :dashboard
  		end	 


  end
  namespace :admin do 
  		resources :events
  end

  namespace :api do
      constraints(host: 'howard.localhost') do
        resources :users, only: [:index , :show] 
        root to: "base#index"
      end  
  end 	

  

  resources :people

  get "/ajax" => "welcome#ajax"
  get "/ajaxtest" => "welcome#ajaxtest"
	get "welcome/say_hello" => "welcome#say"
	get "welcome" => "welcome#index"
	# root "welcome#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  	
end

app/controllers/event_attendees_controller.rb
class EventAttendeesController < ApplicationController
		before_action :set_event
	def index
		@attendees = @event.attendees
	end

	def new
		@attendee = @event.attendees.build		
	end	

	def create
		@attendee = @event.attendees.build(attendees_params)
		if @attendee.save
			flash[:notice] = "新增參加人員"
		   redirect_to event_attendees_path(@event,@attendee)
		else 
			flash[:alert] = "新增人員失敗"
			render :action => :edit
		end	

	end

	def show
		@attendee = @event.attendees.find(params[:id]) 
	end

	def edit
		@attendee = @event.attendees.find(params[:id])
	end

	def update
		@attendee = @event.attendees.find(params[:id])
		if @attendee.update(attendees_params)
			flash[:notice] = "更新成功"
			redirect_to event_attendee_path(@event)
		else
			flash[:alert] = "更新失敗"
			render :action => :edit
		end	
	end

	def destroy
		@attendee = @event.attendees.find(params[:id])
		@attendee.destroy
		flash[:alert] = "刪除成功"
		redirect_to event_attendees_path(@event)

	end







	protected

	def set_event
		@event = Event.find(params[:event_id])
	end

	def attendees_params
		params.require(:attendee).permit(:name, :event_id)
	end
end

app/helpers/event_attendees_helper.rb
module EventAttendeesHelper
end

app/views/event_attendees/edit.html.erb
<h1>Changing Attending</h1>

<% if @attendee.errors.any? %>
	<% @attendee.errors.full_messages.each do |msg| %>
	<div><span style="font-size: 18px">	<%= msg %></span> </div>
	<% end %>
<% end %>


<%= form_for @attendee, :url => event_attendee_path(@event,@attendee.id), :method => :patch do |f| %>
	<div class="form-group" style="font-size: 20px">
		<span ><%= f.label :name %></span>
		<%= f.text_field :name , :class => "form-control" %>
	</div>

	<div class="form-group">
		<%= f.submit :submit_name, :class => "btn btn-success"  %>
	</div>

<% end %>	

app/views/event_attendees/index.html.erb
<h1><%= @event.name %>Attendees list</h1>


<table class="table">
<tr>
<% @attendees.each do |a| %>
</tr>
	<td>
		<%= a.name %>
	</td>
	<td>	
		<%= link_to 'Attendees Detail', event_attendee_path(@event, a), :class => "btn btn-primary" %>
		<%= link_to 'Edit Attendees', edit_event_attendee_path(@event, a), :class => "btn btn-success" %>
		<%= link_to 'Attendees Cancel', event_attendee_path(@event, a),:method => :delete, :class => "btn btn-danger" %>
	</td>
<% end  %>
</table>

<%= link_to 'New Attendees', new_event_attendee_path(@event), :class => "btn btn-success" %>
<%= link_to 'Back to Events List', events_path, :class => "btn btn-primary" %>
<!-- 如果對使用單複數、new_event、edit_event有疑問，多加善用 rake routes -->

app/views/event_attendees/new.html.erb
<h1>Attending Event</h1>

<%= form_for @attendee, :url => event_attendees_path(@event) do |f| %>
	<div class="form-group">
		<%= f.label :name %>
		<%= f.text_field :name , :class => "form-control" %>
	</div>

	<div class="form-group">
		<%= f.submit :submit_name, :class => "btn btn-success"  %>
	</div>

<% end %>	
<%= link_to 'Back to Attendees List', event_attendees_path(@event), :class => "btn btn-default" %>

app/views/event_attendees/show.html.erb
<h1><%= @event.name %> : Attendees</h1>

<table class="table">
<tr>	
</tr>
<td>
<%= @attendee.name %>
</td><br \>
<td>
<%= @attendee.event_id%>
</td>	
</table>






<%= link_to 'Back to Attendees List', event_attendees_path(@event), :class => "btn btn-primary" %>