config/routes.rb
Rails.application.routes.draw do


  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  resources :events do 
  		resources :attendees , :controller => :event_attendees

  		collection do
  			get :latest
  			post :bulk_update
  		end

  		member do 
  			get :dashboard
  		end	 


  end
  namespace :admin do 
  		resources :events
  end

  namespace :api do
      constraints(host: 'howard.localhost') do
        resources :users, only: [:index , :show] 
        root to: "base#index"
      end  
  end 	

  

  resources :people

  get "/ajax" => "welcome#ajax"
  get "/ajaxtest" => "welcome#ajaxtest"
	get "welcome/say_hello" => "welcome#say"
	get "welcome" => "welcome#index"
	# root "welcome#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  	
end

app/models/event.rb
class Event < ApplicationRecord
	validates_presence_of :name
	has_many :attendees
	belongs_to :category
	belongs_to :user
	
	delegate :name, :to => :category , :prefix => true, :allow_nil => true
	
	has_many :event_groupships #實際包含為 has_many :event_groupships, :class_name => "EventGroupships", :foreign_key => "event_id"
	has_many :groups, :through => :event_groupships

	has_attached_file :logo, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
 	validates_attachment_content_type :logo, content_type: /\Aimage\/.*\z/

end

app/controllers/admin/events_controller.rb
class Admin::EventsController < ApplicationController

	before_action :authenticate_user!
	before_action :check_admin

	layout 'admin'

	def index
		@events = Event.all
	end

	protected


    def check_admin
		unless current_user.admin?
			raise ActiveRecord::RecordNotFound
		end	
	end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
	
	before_action :authenticate_user!, :except => [:index]
	before_action :set_event, :only => [:show, :edit, :update, :destroy, :dashboard]
	#GET/events/index
	#GET/events
	def index
		# if params[:group]
		# 	@group = Group.find_by_name(params[:group])
		# 	@events = @group.events.page(params[:page]).per(5)
		# else
		# 	@events = Event.page(params[:page]).per(5)
		# end
		#  以Group的名字進行排序之語法	

		if params[:keyword]
			@events = Event.where( [ "name like ?", "%#{params[:keyword]}%" ] )
		else
			@events = Event.all
		end	

		if params[:order]
			sort_by = (params[:order] == 'name') ? 'name' : 'id'
			@events = @events.order(sort_by)
		end	
		@events = @events.page(params[:page]).per(15)

		# respond_to do |format|
		# 	format.html
		# 	format.xml {
		# 		render :xml => @events.to_xml
		# 	}
		# 	format.json {
		# 		render :json => @events.to_json
		# 	}
		# 	format.atom {
		# 		@feed_title = "My Event List"
		# 	}#index.stom.builder
		# end	
		
		if params[:id]
			@event = Event.find(params[:id]) 
		else	
			@event = Event.new
		end
	end		

	#GET/events/new，因為是新生成，所以name & description內都是空的
	def new
		@event = Event.new
	end	
	#GET events/show/:id，因為是用find method，所以name & description會有原先event的資料
	def show
		@page_title = @event.name

		result = {id: @event.id, name: @event.name, created_at: @event.created_at}

         respond_to do |format|
		    format.html { @page_title = @event.name } # show.html.erb
		    format.xml # show.xml.builder
		    format.json { render :json => result.to_json }
		  end
        
	end	

	def dashboard
	end

	def latest
	  @events = Event.order("id DESC").limit(3)
	end

	#GET events/edit/:id
	def edit

	end	

	def update
		@event.user = current_user
		if params[:remove_upload_file] == "1"
			@event.logo = nil
		end

	  	if @event.update(event_params)#render會導向一個畫面或format

	  		flash[:notice] = "編輯成功"

	   	redirect_to event_path(@event) #到show頁面時，還是要給一個id，show才能找到更新的資料
		
		else 
			flash[:alert] = "編輯失敗"
		    render :action => :edit #"edit"
		end    	
	end

	def destroy
		@event.destroy

		flash[:alert] = "刪除成功"

	  redirect_to events_path
	end

	def bulk_update
		ids = Array(params[:ids])
		events = ids.map{|e| Event.find_by_id(e)}.compact

		if params[:commit] == "Delete"
			events.each {|e| e.destroy}
		elsif params[:commit] == "Publish"
			events.each {|e| e.update(:status => "published")}
		end

		redirect_to events_path
	end

	#POST/events/create
	def create
		@event = Event.new( event_params )
		@events = Event.page(params[:page]).per(15) #因為create在失敗的時候，並沒有送出@events的直，所以必須在失敗時給予@events可送出的直
		@event.user = current_user
		if @event.save

			flash[:notice] = "新增成功"
			
			redirect_to events_url #告訴瀏覽器  HTTP code 303
		else
			flash[:alert] = "新增失敗"
			render :action => :index #new.html.erb
		end	
	end	

	private

	def set_event
		@event = Event.find(params[:id])
	end	
	#params是屬於白名單（正面表列），只有params裡面認定的才會接起來
	def event_params
		params.require(:event).permit( :name, :description, :logo , :user_id ,  :category_id, :group_ids => []  )
	end	
end	

app/helpers/admin/events_helper.rb
module Admin::EventsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<% if @event.errors.any? %>
      <ul>
      <% @event.errors.full_messages.each do |msg| %>
        <h1><li><%= msg %></li></h1>
      <% end %>
      </ul>
<% end %>    


  <%= f.file_field :logo %>

  <% if @event.logo.exists? %>
    <%= check_box_tag "remove_upload_file" , "1" %>覆蓋上傳檔案
  <% end %>

<div class="form-group">
    <%= f.label :name, "Name" %>
    <%= f.text_field :name , :class => "form-control"%>
</div>

<div class="form-group">
	<%= f.label :status, "Status" %>
    <%= f.select :status, [["Published", "published"],["Draft","draft"]] %>
</div>

<div class="form-group">
    <%#= f.label :category_id, "Category" %>
    <%#= f.select :category_id ,Category.all.map{|x| [x.name, x.id]}, {:prompt => "Please Select"}, {:class => "form-control"} %>
    <%#= f.collection_select :category_id ,Category.all ,:id, :name , :class => "form-control", :prompt => "Please Select" %>
    <% Category.all.each do |c| %>
    <%= f.radio_button :category_id , c.id %><%= c.name%>
    <%end %>
</div>

<div class="form-group">
	<%= f.collection_check_boxes(:group_ids, Group.all, :id, :name) %>
</div>
	

<div class="form-group">
    <%= f.label :description, "Description" %>
    <%= f.text_area :description, :class => "form-control" %>
</div>

app/views/events/dashboard.html.erb
<h1><%= @event.name %>  Dashboard</h1>

<ul>
	<li><%= @event.name %></li>
	<li><%= @event.status %></li>
	<li><%= @event.description %></li>

	
</ul>

app/views/events/edit.html.erb
<%= form_for @event, :url => event_path(@event),html: { multipart: true },  :method => :patch do |f| %>
<!-- form_for 前要加上“＝”，才會產生HTML格式的程式碼，才能生成表格，url則是代表要將這張表單往哪裡送 -->
    <%= render :partial => 'form', :locals => { :f => f } %>

    <%= f.submit "Update" %>
<% end %>

app/views/events/index.html.erb
<h1>Events list</h1>
<div>
	<%= t("hello") %> <br><%= t("event") %>
 </div>
<%= form_for @event ,html: { multipart: true } do |f| %>
	<!-- form_for 前要加上“＝”，才會產生HTML格式的程式碼，才能生成表格，url則是代表要將這張表單往哪裡送 -->
    
    <%= render :partial => 'form', :locals => { :f => f } %>

    <%= f.submit "Submit", :class => "btn btn-success" %>
    <%= f.submit "Cancel", :class => "btn btn-default" %>
<% end %>

<br \>

<%= form_tag events_path, :method => :get do %>
  <%= text_field_tag "keyword" %>
  <%= submit_tag "Search" %>
<% end %>

<br \>

	<%= link_to 'latest Events', latest_events_path ,:class => "btn btn-warning" %>

<br \>

	<%= link_to "Sort by numer", events_path(:order => "name"),:class => "btn btn-default" %>
	<%= link_to "Sort by default", events_path,:class => "btn btn-default" %>
<br \>
<%= form_tag bulk_update_events_path do %>

<table class="table">
	
	<td>活動</td>
	<td>發起人</td>
	<td></td>
	
	
	
<tr>
<% @events.each do |event| %>
</tr>
	
	<td>
		<%= check_box_tag "ids[]", event.id,false%>
		<%= event.name %>
	</td>
	<td>
		<%= event.user.try(:short_name)%>
	</td>
	<td>	
		<%= link_to 'Show', event_path(event), :class => "btn btn-success" %>
		<%= link_to 'Attendees', event_attendees_path(event), :class => "btn btn-primary" %>
		<%= link_to 'Edit', events_path(:id => event.id), :class => "btn btn-default" %>
  		<%= link_to 'Delete', event_path(event), :method => :delete, :class => "btn btn-danger" %>
  		<%= link_to 'Dashboard', dashboard_event_path(event), :class => "btn btn-warning" %>
  		

	</td>
<% end %>
</table>
<%= submit_tag "Delete"%>
<%= submit_tag "Publish"%>
<% end %>
<!-- 如果對使用單複數、new_event、edit_event有疑問，多加善用 rake routes -->

<%= paginate @events %>

app/views/events/latest.html.erb
<h1>Latest Events</h1>

<br \>
<ul>
	
	<% @events.each do |e|%>

	  <li><%= e.name %></li>

	<% end %>
</ul>
<%= link_to 'Back to Index', events_path, :class => "btn btn-default" %>

app/views/events/new.html.erb
<%= form_for @event, :url => events_path , html: { multipart: true } do |f| %>
	<!-- form_for 前要加上“＝”，才會產生HTML格式的程式碼，才能生成表格，url則是代表要將這張表單往哪裡送 -->
    
    <%= render :partial => 'form', :locals => { :f => f } %>

    <%= f.submit "Create" %>
<% end %>

app/views/events/show.html.erb
<%= content_for :head do %>
    <%= tag(:meta, :content => @event.name, :property => "og:title") %>
    <%= tag(:meta, :content => "article", :property => "og:type") %>
    <%= tag(:meta, :content => event_url(@event), :property => "og:url") %>
    <%= tag(:meta, :content => "http://www.fhm.com.tw/article?id=19670", :property => "og:image") %>
<% end %>
<div id="fb-root"></div>
	<script>(function(d, s, id) {
	  var js, fjs = d.getElementsByTagName(s)[0];
	  if (d.getElementById(id)) return;
	  js = d.createElement(s); js.id = id;
	  js.src = "//connect.facebook.net/zh_TW/sdk.js#xfbml=1&version=v2.8&appId=1709952185992091";
	  fjs.parentNode.insertBefore(js, fjs);
	}(document, 'script', 'facebook-jssdk'));</script>

	<!-- Your share button code -->
	<div class="fb-like" data-href="http://localhost:3000/events/1" data-layout="standard" data-action="like" data-size="large" data-show-faces="true" data-share="true"></div>






<h1><%= @event.name %></h1>



<%= image_tag @event.logo.url %>
<%= image_tag @event.logo.url(:medium) %>
<%= image_tag @event.logo.url(:thumb) %>

<table class="table">
	<p><%= @event.status %></p>

		<tr>
			<td>Category</td>
			<td>
				<div>
					<span style="font-size: 25px  ">
						<%= @event.category_name %>
					</span>
				</div>
			</td>
			<td></td>
		</tr>


		<td>Group</td>
		
		<% @event.groups.each do |g| %>

		<td>	
			<div>
				<span style="font-size: 25px  ">
					<%=  g.name  %>
				</span>
			</div>
		</td>
	<% end %>
	
</table>
Description: <%= simple_format @event.description %>

<p>
	<%= link_to 'Back to index', events_path,:class => "btn btn-success" %>
</p>
<a class="facebook_share" href="javascript:fbSharer('http://s.nextmedia.com/apple/a.php?i=20160723&amp;sec_id=15335&amp;s=0&amp;a=19707053')"></a>
<!-- <iframe src="https://www.facebook.com/plugins/share_button.php?href=https%3A%2F%2Fdevelopers.facebook.com%2Fdocs%2Fplugins%2F&layout=button_count&size=large&mobile_iframe=false&appId=1709952185992091&width=106&height=28" width="106" height="28" style="border:none;overflow:hidden" scrolling="no" frameborder="0" allowTransparency="true"></iframe> -->