config/routes.rb
Rails.application.routes.draw do


  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  resources :events do 
  		resources :attendees , :controller => :event_attendees

  		collection do
  			get :latest
  			post :bulk_update
  		end

  		member do 
  			get :dashboard
  		end	 


  end
  namespace :admin do 
  		resources :events
  end

  namespace :api do
      constraints(host: 'howard.localhost') do
        resources :users, only: [:index , :show] 
        root to: "base#index"
      end  
  end 	

  

  resources :people

  get "/ajax" => "welcome#ajax"
  get "/ajaxtest" => "welcome#ajaxtest"
	get "welcome/say_hello" => "welcome#say"
	get "welcome" => "welcome#index"
	# root "welcome#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  	
end

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= @page_title || "Event application"%></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' =>true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  </head>
  <body>
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <h1>Admin Interface</h1> 
             
        <% if flash[:notice].present? %>
          <div class="alert alert-success" role ="alert">
            <p style="color: green"><%= flash[:notice] %></p>
          </div> 
        <% end %>
        
        <% if flash[:alert].present? %>  
          <div class="alert alert-danger" role ="alert"> 
            <p style="color: red"><%= flash[:alert] %></p>
          </div>
        <% end %>  

        <%= link_to "中文版", :controller => controller_name, :action => action_name, :locale => "zh-TW" %>
        <%= link_to "English", :controller => controller_name, :action => action_name, :locale => "en" %>
        <%= yield %>
      </div>
    </div>
  </div>


  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html prefix="og: http://ogp.me/ns#">
  <head>
    <title><%= @page_title || "Event application"%></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' =>true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= yield :head%>    

  </head>
  <body>
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <% if flash[:notice].present? %>
          <div class="alert alert-success" role ="alert">
            <p style="color: green"><%= flash[:notice] %></p>
          </div> 
        <% end %>
        
        <% if flash[:alert].present? %>  
          <div class="alert alert-danger" role ="alert"> 
            <p style="color: red"><%= flash[:alert] %></p>
          </div>
        <% end %> 

        <% if current_user %>

        Hi, <%= current_user.short_name %>
          <%= link_to('登出', destroy_user_session_path, :method => :delete) %> |
          <%= link_to('修改密碼', edit_registration_path(:user)) %>
        <% else %>
          <%= link_to('註冊', new_registration_path(:user)) %> |
          <%= link_to('登入', new_session_path(:user)) %> |
          <%= link_to "Facebook log In", user_facebook_omniauth_authorize_path %>
        <% end %> 
        <%= link_to "中文版", :controller => controller_name, :action => action_name, :locale => "zh-TW" %>
        <%= link_to "English", :controller => controller_name, :action => action_name, :locale => "en" %>
        <%= image_tag current_user.gravatar_url %>
        

                <%= yield %>
                <% if current_user && current_user.admin? %>
                  <%= link_to "Admin Space" , admin_events_path , :class => "btn btn-warning" %>
                <% end %>
              </div>
            </div>
          </div>


        <!-- <div id="fb-root"></div>
        <script>(function(d, s, id) {
          var js, fjs = d.getElementsByTagName(s)[0];
          if (d.getElementById(id)) return;
          js = d.createElement(s); js.id = id;
          js.src = "//connect.facebook.net/zh_TW/sdk.js#xfbml=1&version=v2.8&appId=1709952185992091";
          fjs.parentNode.insertBefore(js, fjs);
        }(document, 'script', 'facebook-jssdk'));
        </script> -->

  </body>
</html>